# Generated by Django 6.0.5 on 2026-05-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Accessory', 'Accessory'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes'), ('Watch', 'Watch'), ('Toy', 'Toy'), ('Sports', 'Sports'), ('Book', 'Book'), ('Gaming', 'Gaming'), ('Fitness', 'Fitness'), ('Furniture', 'Furniture')], max_length=50),
        ),
    ]
